(ns xi.ext.dialkit-css
  "Compile-time macro that inlines the dialkit stylesheet
   (resources/dialkit/dial.css, generated by `bb dialkit:css`) into the
   ClojureScript bundle. The browser overlays (style-editor, design-mode) inject
   it as a <style> tag before mounting a dialkit panel, since the target page
   does not load clj-ui-framework's CSS.

   resources/ is not on the classpath, so the file is read by repo-relative
   path at compile time — mirrors xi.ext.style-editor-js."
  (:require [clojure.java.io :as io]))

(def ^:private css-file "resources/dialkit/dial.css")

(defmacro inline-dialkit-css
  "Read the generated dialkit CSS at compile time and return it as a string
   literal, or \"\" when the resource is absent."
  []
  (let [f (io/file css-file)]
    (if (.exists f) (slurp f) "")))
