#!/usr/bin/env bb
;; Generate resources/dialkit/dial.css — the injectable stylesheet for the
;; dialkit live-tuning panel (window.__uiDial) used by the browser overlays
;; (style-editor, design-mode).
;;
;; dialkit ships its component CSS as clj-ui-framework's src/ui/dial.css, which
;; is fully token-driven (var(--fg-0), var(--bg-0), var(--size-2), …). Those
;; tokens live in the framework's generated dist/theme.css, split across a
;; :root layer and per-theme override blocks. The overlays inject into an
;; arbitrary target page that does NOT load the framework CSS, so we resolve
;; the ~25 tokens dial.css actually uses (following var() chains, preferring
;; the dark-theme layer) down to concrete values and emit them scoped to
;; .dialkit-root, then append dial.css verbatim.
;;
;; Nothing here is hand-maintained: rerun `bb dialkit:css` after bumping the
;; clj-ui-framework pin to pick up token/CSS changes.
;;
;; The framework source is resolved from the pinned gitlib (no local checkout
;; required): `bb dialkit:css` passes CLJ_UI_FRAMEWORK = the gitlib dir for the
;; deps.edn :git/sha. dist/theme.css is a gitignored build artifact absent from
;; the gitlib, so when it is missing we regenerate the :root / dark token blocks
;; from the committed src/theme/tokens.edn via the framework's own ui.css.gen.
;; Set CLJ_UI_FRAMEWORK to a local checkout to regenerate against uncommitted
;; framework edits.

(require '[clojure.string :as str]
         '[clojure.edn :as edn]
         '[clojure.java.io :as io])

(defn framework-dir []
  (or (System/getenv "CLJ_UI_FRAMEWORK")
      (let [sha  (-> (slurp "deps.edn") edn/read-string
                     (get-in [:deps 'io.github.floscr/clj-ui-framework :git/sha]))
            base (or (System/getenv "GITLIBS")
                     (str (System/getProperty "user.home") "/.gitlibs"))]
        (str base "/libs/io.github.floscr/clj-ui-framework/" sha))))

(def framework (framework-dir))
(def dial-css  (str framework "/src/ui/dial.css"))
(def out-file  "resources/dialkit/dial.css")

(defn theme-css-str
  "The framework theme CSS: prefer a built dist/theme.css (local checkout);
   otherwise regenerate the :root / dark token blocks from the committed
   tokens.edn via the framework's own ui.css.gen (gitlib has no dist/)."
  []
  (let [dist (str framework "/dist/theme.css")]
    (if (.exists (io/file dist))
      (slurp dist)
      (let [tokens-edn (str framework "/src/theme/tokens.edn")]
        (load-file (str framework "/src/ui/css/gen.clj"))
        (let [read-tokens       (resolve 'ui.css.gen/read-tokens)
              tokens->css-block (resolve 'ui.css.gen/tokens->css-block)
              generate-scales   (resolve 'ui.css.gen/generate-scales)
              {:keys [tokens themes scales]} (read-tokens tokens-edn)]
          (str ":root {\n" (tokens->css-block tokens) "\n"
               (generate-scales scales) "\n}\n\n"
               "[data-theme=\"dark\"] {\n"
               (tokens->css-block (:dark themes)) "\n}\n"))))))

(defn parse-decls [body]
  (into {} (for [m (re-seq #"(--[a-zA-Z0-9-]+)\s*:\s*([^;]+);" body)]
             [(nth m 1) (str/trim (nth m 2))])))

(defn -main []
  (let [theme   (theme-css-str)
        dialcss (slurp dial-css)
        blocks  (re-seq #"(?s)([^{}]+)\{([^{}]*)\}" theme)
        root    (atom {})
        dark    (atom {})
        _ (doseq [[_ sel body] blocks]
            (let [s (str/trim sel) decls (parse-decls body)]
              (cond
                (= s ":root") (swap! root merge decls)
                (or (= s "[data-theme=\"dark\"]")
                    (= s ":root:not([data-theme=\"light\"])"))
                (swap! dark merge decls))))
        lookup (fn [tok] (or (get @dark tok) (get @root tok)))
        resolve-val
        (fn resolve-val [v seen]
          (str/replace v #"var\((--[a-zA-Z0-9-]+)(?:\s*,\s*([^()]*))?\)"
            (fn [[_ tok fallback]]
              (if (seen tok)
                (or fallback "")
                (if-let [dv (lookup tok)]
                  (resolve-val dv (conj seen tok))
                  (or fallback ""))))))
        ;; --dial-color-solid is a local var defined inside dial.css itself;
        ;; --font-mono is not in the framework tokens, so we supply a fallback.
        used (->> (re-seq #"var\((--[a-zA-Z0-9-]+)" dialcss)
                  (map second) distinct sort
                  (remove #{"--dial-color-solid" "--font-mono"}))
        unresolved (remove lookup used)
        _ (when (seq unresolved)
            (binding [*out* *err*]
              (println "WARN unresolved dialkit tokens:" (vec unresolved))))
        token-lines (for [t used] (str "  " t ": " (str/trim (resolve-val (lookup t) #{t})) ";"))
        token-block (str ".dialkit-root {\n"
                         "  --font-mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;\n"
                         (str/join "\n" token-lines) "\n}\n")
        content (str "/* GENERATED by scripts/gen-dialkit-css.clj — do not edit.\n"
                     "   dialkit component CSS (clj-ui-framework src/ui/dial.css) + resolved\n"
                     "   dark-theme tokens (clj-ui-framework dist/theme.css :root/[data-theme]).\n"
                     "   Regenerate with `bb dialkit:css`. */\n\n"
                     token-block "\n" dialcss)]
    (io/make-parents out-file)
    (spit out-file content)
    (println "wrote" out-file (str "(" (count content) " bytes, " (count used) " tokens)"))))

(-main)
