#!/usr/bin/env bb
;; Generate resources/dialkit/dial.css — the injectable stylesheet for the
;; dialkit live-tuning panel (window.__uiDial) used by the browser overlays
;; (style-editor, design-mode).
;;
;; dialkit ships its component CSS as clj-ui-framework's src/ui/dial.css, which
;; is fully token-driven (var(--fg-0), var(--bg-0), var(--size-2), …). Those
;; tokens live in the framework's generated dist/theme.css, split across a
;; :root layer and per-theme override blocks. The overlays inject into an
;; arbitrary target page that does NOT load the framework CSS, so we resolve
;; the ~25 tokens dial.css actually uses (following var() chains, preferring
;; the dark-theme layer) down to concrete values and emit them scoped to
;; .dialkit-root, then append dial.css verbatim.
;;
;; Nothing here is hand-maintained: rerun `bb dialkit:css` after bumping the
;; clj-ui-framework checkout to pick up token/CSS changes.

(require '[clojure.string :as str]
         '[clojure.java.io :as io])

(def framework "/home/floscr/Code/Projects/clj-ui-framework")
(def theme-css (str framework "/dist/theme.css"))
(def dial-css  (str framework "/src/ui/dial.css"))
(def out-file  "resources/dialkit/dial.css")

(defn parse-decls [body]
  (into {} (for [m (re-seq #"(--[a-zA-Z0-9-]+)\s*:\s*([^;]+);" body)]
             [(nth m 1) (str/trim (nth m 2))])))

(defn -main []
  (let [theme   (slurp theme-css)
        dialcss (slurp dial-css)
        blocks  (re-seq #"(?s)([^{}]+)\{([^{}]*)\}" theme)
        root    (atom {})
        dark    (atom {})
        _ (doseq [[_ sel body] blocks]
            (let [s (str/trim sel) decls (parse-decls body)]
              (cond
                (= s ":root") (swap! root merge decls)
                (or (= s "[data-theme=\"dark\"]")
                    (= s ":root:not([data-theme=\"light\"])"))
                (swap! dark merge decls))))
        lookup (fn [tok] (or (get @dark tok) (get @root tok)))
        resolve-val
        (fn resolve-val [v seen]
          (str/replace v #"var\((--[a-zA-Z0-9-]+)(?:\s*,\s*([^()]*))?\)"
            (fn [[_ tok fallback]]
              (if (seen tok)
                (or fallback "")
                (if-let [dv (lookup tok)]
                  (resolve-val dv (conj seen tok))
                  (or fallback ""))))))
        ;; --dial-color-solid is a local var defined inside dial.css itself;
        ;; --font-mono is not in the framework tokens, so we supply a fallback.
        used (->> (re-seq #"var\((--[a-zA-Z0-9-]+)" dialcss)
                  (map second) distinct sort
                  (remove #{"--dial-color-solid" "--font-mono"}))
        unresolved (remove lookup used)
        _ (when (seq unresolved)
            (binding [*out* *err*]
              (println "WARN unresolved dialkit tokens:" (vec unresolved))))
        token-lines (for [t used] (str "  " t ": " (str/trim (resolve-val (lookup t) #{t})) ";"))
        token-block (str ".dialkit-root {\n"
                         "  --font-mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;\n"
                         (str/join "\n" token-lines) "\n}\n")
        content (str "/* GENERATED by scripts/gen-dialkit-css.clj — do not edit.\n"
                     "   dialkit component CSS (clj-ui-framework src/ui/dial.css) + resolved\n"
                     "   dark-theme tokens (clj-ui-framework dist/theme.css :root/[data-theme]).\n"
                     "   Regenerate with `bb dialkit:css`. */\n\n"
                     token-block "\n" dialcss)]
    (io/make-parents out-file)
    (spit out-file content)
    (println "wrote" out-file (str "(" (count content) " bytes, " (count used) " tokens)"))))

(-main)
